modified:   README 	modified:   shh 	modified:   shh.1.gz 	modified:   shh.1.md

diff --git a/shh b/shh
--- a/shh
+++ b/shh
@@ -28,7 +28,7 @@ readonly reset='\e[0m'
 
 _version()
 {
-    echo -e "$(basename $0) - The shell script helper - version $VERSION" >&2
+    echo -e "$(basename $0) - The shell program helper utility - version $VERSION" >&2
 }
 
 _usage_short()
@@ -56,9 +56,9 @@ _usage_long()
     |Commands:
     |   new    setup a new working directory
     |   del    delete all working files in directory
+    |   lf     list all functions in working dir
+    |   lv     list all variables in working dir
     |   merge  "compile" all working files together
-    |   lf    list all functions in working dir
-    |   lv    list all variables in working dir
     |   
     |Command Options:
     |   new:
@@ -119,9 +119,9 @@ _setup()
         fi
 
 		# Set native files, give an apropriate version number, and open $executive in an editor
-        { touch functions vars ${executive}; } #|| ex=1; _exit "data error"
-        { echo "readonly VERSION=1.0" > vars; } #|| ex=1; _exit "data error"
-        { echo "#!/bin/bash" > "${executive}" && chmod +x "${executive}"; } #|| ex=1; _exit "data error"
+        { touch functions vars ${executive}; } || ex=1; _exit "data error"
+        { echo "readonly VERSION=1.0" > ./'vars'; } || ex=1; _exit "data error"
+        { echo -e "#!/bin/bash\nsource vars\nsource functions" > ./"${executive}" && chmod +x ./"${executive}"; } || ex=1; _exit "data error"
         ${EDITOR} ${executive}
 }
 
@@ -136,7 +136,6 @@ _list_vars()
 		esac
 	    echo "$(echo -e ${color} $(echo $line | cut -d "=" -f 1 | cut -d " " -f 2 ) ${reset})$(echo $line | cut -d "=" -f 2 | sed 's/#.*//')"
 	done < ./'vars'
-    #sed '/^\s*$/d'
 }
 
 # Show functions' "order of opertations"
@@ -148,6 +147,13 @@ _list_functions()
             echo -e " ${color}(${n})${reset}\t$(echo $line | cut -d ' ' -f 2)";
 			n=$(($n + 1))
 		done < ./'functions' | sed '1 d' | sed '$ d'
+}
+
+# Create new function
+_new_function()
+{
+    # index
+    :
 }
 
 # Native files merged
@@ -191,7 +197,6 @@ _sweep()
     _special
 }
 
-
 # "Compile"
 # Checks to see if "native" files still exsist, if so, "merges" all files together in a certain order, then cleans up the place.
 _compile()
@@ -208,7 +213,15 @@ _compile()
 
 # Options
 QUIET=0
-{ [[ -z $EDITOR && -x /usr/bin/vim ]] && EDITOR=vim; } || { [[ -x /usr/bin/nano ]] && EDITOR=nano; }
+
+# Editor 
+if [[ -n $EDITOR ]]; then
+    EDITOR=$EDITOR
+elif [[ -x /usr/bin/vim ]]; then
+    EDITOR=vim
+elif [[ -x /usr/bin/nano ]]; then
+    EDITOR=nano
+fi
 
 if [ $# -eq 0 ]; then
 		_usage
