modified:   README 	modified:   shh

diff --git a/shh b/shh
--- a/shh
+++ b/shh
@@ -30,6 +30,15 @@ INIT=./'.parents'
 PARENT=( 'curr' 'refs' '.index')
 CHILD=('vars' 'functions')
 
+# Define existing values
+if [[ -d $INIT ]]; then
+    INDEX=$INIT/${PARENT[0]}/${PARENT[2]}
+    EXECUTIVE=$(cat $INDEX | head -n 1 | cut -d " " -f 3)
+    VARIABLES=$INIT/${PARENT[0]}/${CHILD[0]}
+    FUNCTIONS=$INIT/${PARENT[0]}/${CHILD[1]}
+    [[ $? -ne 0 ]] && return 1
+fi
+
 # ! - All non zero return values are currently at set to 1, and since many things are happening,
 # and the use of silent mode is an option, return values should offer more information.
 # HEY, THIS NEEDS DONE ASSHOLE!!!
@@ -117,13 +126,57 @@ _read_man(){
 
 # Remove all working files/directories
 _remove(){
+    
+    # Removes  all functions
+    del_functions(){
+        local allf f
+        allf=( $(cat $FUNCTIONS | cut -d ' ' -f 2) )
+        while read; do
+            for f in ${allf[@]}; do
+                if [[ -e $f ]]
+                then
+                    if rm "$f"
+                    then
+                        [[ $? -eq 0 ]] || return 1
+                        return 0
+                    fi
+                fi
+            done
+        done < $FUNCTIONS
+    }
+
+    # Removes all files indexed files
+    del_indexed(){
+        local alli i
+        alli=( $(cat $INDEX | cut -d ' ' -f 3) )
+        while read; do
+            for i in ${alli[@]}; do
+                if [[ -e $i ]]
+                then
+                    if rm "$i"
+                    then
+                        [[ $? -eq 0 ]] || return 1
+                    fi
+                fi
+            done
+        done < $INDEX
+    }
+
+    while :; do
+        del_functions; del_indexed; break
+    done
+    
+    [[ $? -eq 0 ]] && rm -r "$INIT" || return 1
+}
+
+_remove0(){
     local line0 line1 tmpf
     tmpf=$(mktemp -p /tmp "shh.XXXXXXXXXXXXXX")
     ret=$?
     
     while read -r line0; do
         echo $line0 | cut -d " " -f 2 >> $tmpf #|| ex=1; _exit "failed to fill tempfile from .index"
-    done < ./.parents/curr/.index
+    done < $INDEX
 
     while read -r line1; do
         rm -rv $line1 || ex=1; _exit "failed to remove working files."
@@ -131,7 +184,6 @@ _remove(){
     rm -rv $INIT $tmpf
 }
 
-# ! - init directory
 # This will setup a hidden dir, set all parents inside,
 # make all children, then nest them inside of the parents.
 _setup_init(){
@@ -150,17 +202,16 @@ _setup_init(){
         [[ $? -eq 0 ]] || echo $?
 
         # Start filling stuff in ..
-        echo "readonly VERSION=1.0" > $VARIABLES echo $? #|| ex=1; _exit "failed to setup $VARIABLES"
-        echo -e "#!/bin/bash\nsource $VARIABLES\nsource $FUNCTIONS\n" >> $EXECUTIVE echo $? #|| ex=1; _exit "failed to setup $FUNCTIONS"
+        echo "readonly VERSION=1.0" > $VARIABLES #|| ex=1; _exit "failed to setup $VARIABLES"
+        echo -e "#!/bin/bash\nsource ${VARIABLES}\nsource ${FUNCTIONS}\n" >> $EXECUTIVE #|| ex=1; _exit "failed to setup $FUNCTIONS"
+        chmod +x $executive
     }
 
     _make_init_dir(){
         # Any additional argument is considered a name for the executive
         if [[ $1 ]]
         then
-            case "$1" in
-                *)  executive="./${1}" || echo $? ;;
-            esac
+            executive="$1"
         else
             # Get a name for the executive
             local name
@@ -199,7 +250,7 @@ _setup_init(){
             echo -e -n "[CONFIRM] ${color}[y/n]${reset}: "
             while read ans0; do case "$ans0" in
                 n|N|no|NO) return 1 ;;
-                y|Y|yes|YES) _remove && _make_init_dir && return 0 || return 1 ;;
+                y|Y|yes|YES) _remove && _make_init_dir "$1" && return 0 || return 1 ;;
                 *) return 1 ;;
             esac done
         }
@@ -213,31 +264,31 @@ _setup_init(){
         esac done
     }
 
-    [[ ! -d $INIT ]] && _make_init_dir && return 0
-    [[ -d $INIT ]] && _has_init_dir && return 0
+    [[ ! -d $INIT ]] && _make_init_dir "$1" && return 0
+    [[ -d $INIT ]] && _has_init_dir "$1" && return 0
     return 1
 }
 
 # Show variable information
 _list_vars(){
-	[[ ! -f ./.parents/curr/vars ]] && { ex=1; _exit "no variables to list"; }
+	[[ ! -f $VARIABLES ]] && { ex=1; _exit "no variables to list"; }
     echo -e "${color}VARIABLES:${reset}"
     while read -r line; do 
         case $line in
             ''|\#*) continue ;;
 		esac
 	    echo "$(echo -e ${color} $(echo $line | cut -d "=" -f 1 | cut -d " " -f 2 ) ${reset})$(echo $line | cut -d "=" -f 2 | sed 's/#.*//')"
-	done < ./.parents/curr/vars
+	done < $VARIABLES #./.parents/curr/vars
 }
 
 # Show functions' "order of opertations"
 _list_functions(){
-    [[ ! -f ./.parents/curr/functions ]] && { ex=1; _exit "no functions to list"; }
+    [[ ! -f $FUNCTIONS ]] && { ex=1; _exit "no functions to list"; }
     echo -e "${color}FUNCTIONS:${reset}" && \
-        while read line; do 
-            echo -e " ${color}(${n})${reset}\t$(echo $line | cut -d ' ' -f 2)";
+        while read -r line; do 
+            echo -e " ${color}(${n})${reset}\t$(echo $line | cut -d ' ' -f 2)" >&2;
 			n=$(($n + 1))
-		done < ./.parents/curr/functions | sed '1 d' | sed '$ d'
+		done < $FUNCTIONS #./.parents/curr/functions #| sed '1 d' | sed '$ d'
 }
 
 # ! - Create new function
@@ -247,55 +298,29 @@ _add_function(){
     # Handle index
 }
 
-# "Compile"
-# Checks to see if "native" files still exsist, if so, merge all files together, then clean up the place.
+# This function will merge all working files together, in order, by index.
+# Then cleans up the place, to leave behind one working program.
 _compile(){
-    # Native files merged
-    _vars(){
-        local tmpvars
-        tmpvars=$(mktemp -p /tmp "shh.XXXXXXXXXXXXXX")
-        cat ${executive} | head -n 1 > $tmpvars && cat vars >> $tmpvars
-        [[ $? -ne 0 ]] && ex=1; _exit "vars not cooperating"
-    }
+   local tmpm funcs line
+   tmpm=$(mktemp -p /tmp "shh.XXXXXXXXXXXXXX") 
+   [[ $? -eq 0 ]] || return 1
 
-    _functions(){
-        local tmpfuncs
-        tmpfuncs=$(mktemp -p /tmp "shh.XXXXXXXXXXXXXX")
-        while read line; do 
-            echo $line | cut -d " " -f 2 | sed 's/#.*//g'
-        done < ./functions | sed '1d;$d' > $tmpfuncs
-    	[[ $? -ne 0 ]] && ex=1; _exit "functions not cooperating"
-    }
-
-    # Special files handled
-    _special(){
-        local found man
-    	for found in ${all_files[@]}; do case "$found" in
-            "$rawman") rm "$rawman" || ex=1; _exit "man page immovable" ;;
-            _*) rm ./_* ;;
-        esac done
-    }
-
-    # Finish him
-    _sweep(){
-        # Functions
-        { cat $tmpfuncs >> $tmpvars && rm $tmpfuncs $tmpvars; } || { ex=1; _exit "could not sweep functions"; }
-		# Executive
-        { sed -i '1,4 d' $executive && cat $executive >> $tmpvars; } && { rm "${executive}"; } || { ex=1; _exit "unable to sweep executive"; }
-        { mv $tmpvars $executive && chmod +x $executive && rm vars functions; } || { ex=1; _exit "unable to sweep vars"; }
-        [[ $? -ne 0 ]] && { ex=1; _exit "unable to '_sweep'"; }
-        _special
-    }
-
-    local n_file all_files
-    all_files=( $(ls .) )
-	for n_file in ${all_files[@]}
-	do case "$n_file" in
-        vars) _vars ;;
-		functions) _functions ;;
-	esac done
-	[[ $? -ne 0 ]] && { ex=1; _exit "Compilation failure"; } # exit-code "system" needed
-    _sweep
+   if cat $EXECUTIVE | head -n 1 > $tmpm
+   then
+       if cat $VARIABLES >> $tmpm
+       then
+           while read -r line; do
+               cat $(echo $line | cut -d " " -f 2) #| sed 's/#.*//g')
+           done <"$FUNCTIONS" >> $tmpm #| sed '1d;$d' >> $tmpm
+           [[ $? -eq 0 ]] || return 1
+           if rm $EXECUTIVE && mv $tmpm $EXECUTIVE && chmod +x $EXECUTIVE
+           then
+               # Future executive is now current executive
+               EXECUTIVE=$(echo $EXECUTIVE | cut -d "/" -f 2)
+               mv ./$EXECUTIVE /tmp && _remove && mv /tmp/$EXECUTIVE .
+           fi
+       fi
+   fi
 }
 
 # Options
