new file:   .gitignore 	modified:   shh

diff --git a/shh b/shh
--- a/shh
+++ b/shh
@@ -25,6 +25,11 @@ readonly VERSION=1.0
 readonly color='\e[32m'
 readonly reset='\e[0m'
 
+declare -a PARENT CHILD
+INIT=./'.parents'
+PARENT=( 'curr' 'refs' '.index')
+CHILD=('vars' 'functions')
+
 # ! - All non zero return values are currently at set to 1, and since many things are happening,
 # and the use of silent mode is an option, return values should offer more information.
 # HEY, THIS NEEDS DONE ASSHOLE!!!
@@ -110,121 +115,129 @@ _read_man(){
     man 1 shh
 }
 
-# Remove all native files
+# Remove all working files/directories
 _remove(){
-    _remove_all()
-	{
-        # ! if functions contains valid data
-        # ! parents
-        local ret=$?
-        { while read line; do rm "$(cut -d ' ' -f 2)"; done < ./functions; }
-		if [[ $ret = 0 ]]; then 
-            rm ./vars ./functions "./${executive}"
-            if [[ $? -ne 0 ]]; then 
-                ex=1; _exit "failed to remove working files"
-            else
-                return 0
-            fi
-        fi
-	}
+    local line0 line1 tmpf
+    tmpf=$(mktemp -p /tmp "shh.XXXXXXXXXXXXXX")
+    ret=$?
     
-    if [ $QUIET = 0 ]; then
-        # Confirmation required
-		local conf ans
-        echo -e -n "CONFIRM ${color}[ y | n ]: ${reset}"
-		read conf
-        for ans in "${conf}"; do case "$1" in
-            n|N) ex=1; _exit "User aborted action" ;;
-            y|Y) _remove_all ;;
-        esac done 
-    fi
-	
-    _remove_all
-    [ $? -ne 0 ] && { ex=1; _exit "failed to remove working files"; }
+    while read -r line; do
+        echo $line | cut -d " " -f 2 >> $tmpf || ex=1; _exit "failed to fill tempfile from .index"
+    done < ./.parents/curr/.index
+
+    while read -r line1; do
+        rm -rv $line1 || ex=1; _exit "failed to remove working files."
+    done < $tmpf
+    rm -rv $INIT $tmpf
 }
 
 # ! - init directory
+# This will setup a hidden dir, set all parents inside,
+# make all children, then nest them inside of the parents.
 _setup_init(){
-    init_dir=./.parents
-    parent_dirs=${init_dir}/{curr,refs}
-    funcs=${init_dir}/curr/functions
-    vars=${init_dir}/curr/vars
-    ls_init_dir=( $(ls ${init_dir}) )
-    local files
-    
-    if [[ ! ./.parents ]]; then 
-        mkdir -p ${parent_dirs}
-    else
-        ex=1; exit ""
-    fi
-    
-    touch ${funcs} ${vars}
-    _index(){ md5sum $x >> ${init_dir}/index && x=$(cut -d " " -f 2); }
-    for files in ${ls_init_dir[@]}; do case "$1" in
-        "$funcs") x=${funcs}; _index ;;
-        "$vars") x=${vars}$; _index ;;
-    esac done
-}
+    # Do random things to end this function.
+    _other(){
+        INDEX=$INIT/${PARENT[0]}/${PARENT[2]}
+        VARIABLES=$INIT/${PARENT[0]}/${CHILD[0]}
+        FUNCTIONS=$INIT/${PARENT[0]}/${CHILD[1]}
+        EXECUTIVE=$executive
+        
+        _get_index(){ grep -n $x $INDEX | cut -d " " -f 3; }
+        
+        readonly EXECUTIVE=$(x=$EXECUTIVE;_get_index)
+        readonly FUNCTIONS=$(x=$FUNCTIONS;_get_index)
+        readonly VARIABLES=$(x=$VARIABLES;_get_index)
+        [[ $? -eq 0 ]] || echo $?
 
-# Setup a new working directory
-_setup(){
-    # ! - Check if in a clean working directory
-    #[[ $CLEAN = 1 ]] 
-    
-    # Check if a working setup exists
-    # ! - Check if parents exist
-    local has
-    if [[ -f ./functions && -f ./vars ]]; then
-        if [[ $QUIET = 0 ]]; then
-            _warning "You already appear to to be in a working directory, overwrite?: "
-            while read has; do case "$has" in
-                n|N) ex=1; _exit "user aborted action" ;;
-                y|Y) _remove; break ;;
-                *) ex=1; _exit "user response invalid" ;;
-            esac done
+        # Start filling stuff in ..
+        echo "readonly VERSION=1.0" > $VARIABLES || ex=1; _exit "failed to setup $VARIABLES"
+        echo -e "#!/bin/bash\nsource $VARIABLES\nsource $FUNCTIONS\n" >> $EXECUTIVE || ex=1; _exit "failed to setup $FUNCTIONS"
+    }
+
+    _make_init_dir(){
+        # Any additional argument is considered a name for the executive
+        if [[ $1 ]]
+        then
+            case "$1" in
+                *)  executive="./${1}" || echo $? ;;
+            esac
         else
-            ex=1; _exit ""
+            # Get a name for the executive
+            local name
+            echo -e -n "${color}[NAME]: ${reset}"
+            while read name; do case $name in
+                *) executive="./${name}" || echo $?; break ;;
+            esac done
         fi
-    fi
 
-    # Get EXECUTIVE name
-    if [[ $QUIET = 1 ]]; then
-        executive=prog
-    elif [[ -z $1 ]]; then
-        echo -e -n "${color}[NAME]:${reset} "; read executive
-    else
-        case "$1" in
-            *) executive="$1"; shift ;;
-        esac
-    fi
-    
-    # Set native files, give an apropriate version number, and open $executive in an editor
-    { touch functions vars ${executive}; } && { echo "readonly VERSION=1.0" > ./'vars'; }
-    [[ $? -ne 0 ]] && { ex=1; _exit "data error"; }
-    { echo -e "#!/bin/bash\nsource vars\nsource functions" > "./${executive}" && chmod +x "./${executive}"; }
-    [[ $? -eq 0 ]] && ${EDITOR} ${executive}
+        # Make and index all.
+        declare -A all
+        if mkdir -p $INIT/{${PARENT[0]},${PARENT[1]}}
+        then
+            if a=$INIT/${PARENT[0]}/${PARENT[2]}; touch $a
+            then
+                if b=$executive; touch $b; md5sum $b >> $a
+                then
+                    if c=$INIT/${PARENT[0]}/${CHILD[0]}; touch $c; md5sum $c >> $a
+                    then
+                        if d=$INIT/${PARENT[0]}/${CHILD[1]}; touch $d; md5sum $d >> $a
+                        then
+                            _other
+                        fi
+                    fi
+                fi
+            fi
+        fi
+    }
+   
+    # Check if Parents exist,
+    # if so, return a non zero value, and prompt the user (if not in '--silent' mode).
+    _has_init_dir(){
+        # Confirmation needed to remove parents.
+        _confirm(){
+            local ans0
+            echo -e -n "[CONFIRM] ${color}[y/n]${reset}: "
+            while read ans0; do case "$ans0" in
+                n|N|no|NO) return 1 ;;
+                y|Y|yes|YES) _remove && _make_init_dir && return 0 || return 1 ;;
+                *) return 1 ;;
+            esac done
+        }
+        
+        local ans1
+        echo -e -n "You apperar to already be in a working directoy, overwrite? [y/n]: "
+        while read ans1; do case "$ans1" in
+            n|N|no|NO) echo $? ; break ;;
+            y|Y|yes|YES) _confirm || echo $? ; break ;;
+            *) echo "$?" ; break ;;
+        esac done
+    }
+
+    [[ ! -d $INIT ]] && _make_init_dir && return 0
+    [[ -d $INIT ]] && _has_init_dir && return 0
+    return 1
 }
 
 # Show variable information
 _list_vars(){
-	[[ ! -f ./'vars' ]] && { ex=1; _exit "no variables to list"; }
+	[[ ! -f ./.parents/curr/vars ]] && { ex=1; _exit "no variables to list"; }
     echo -e "${color}VARIABLES:${reset}"
     while read -r line; do 
         case $line in
             ''|\#*) continue ;;
 		esac
 	    echo "$(echo -e ${color} $(echo $line | cut -d "=" -f 1 | cut -d " " -f 2 ) ${reset})$(echo $line | cut -d "=" -f 2 | sed 's/#.*//')"
-	done < ./'vars'
+	done < ./.parents/curr/vars
 }
 
 # Show functions' "order of opertations"
 _list_functions(){
-    [[ ! -f ./'functions' ]] && { ex=1; _exit "no functions to list"; }
+    [[ ! -f ./.parents/curr/functions ]] && { ex=1; _exit "no functions to list"; }
     echo -e "${color}FUNCTIONS:${reset}" && \
         while read line; do 
             echo -e " ${color}(${n})${reset}\t$(echo $line | cut -d ' ' -f 2)";
 			n=$(($n + 1))
-		done < ./'functions' | sed '1 d' | sed '$ d'
+		done < ./.parents/curr/functions | sed '1 d' | sed '$ d'
 }
 
 # ! - Create new function
@@ -243,18 +256,19 @@ _new_function(){
 # Native files merged
 _vars(){
     local tmpvars
-    tmpvars=$(mktemp -p /tmp "shh.XXXXXXXXXXXXXX") || ex=1; _exit "yolo v"
-    cat "./${executive}" | head -n 1 > $tmpvars && cat ./vars >> $tmpvars
-    [ $? -eq 0 ] || ex=1; _exit "vars not cooperating"
+    tmpvars=$(mktemp -p /tmp "shh.XXXXXXXXXXXXXX") #|| ex=1; _exit "yolo v"
+    cat ${executive} | head -n 1 > $tmpvars && cat vars >> $tmpvars
+    [[ $? -ne 0 ]] && ex=1; _exit "vars not cooperating"
 }
 
 _functions(){
     local tmpfuncs
-    tmpfuncs=$(mktemp -p /tmp "shh.XXXXXXXXXXXXXX") || ex=1; _exit "yolo f"
-    while read line; do
-        cat $(cut -d " " -f 2) > $tmpfuncs
-	done < ./functions
-	[ $? -eq 0 ] || ex=1; _exit "functions not cooperating"
+    tmpfuncs=$(mktemp -p /tmp "shh.XXXXXXXXXXXXXX")
+    #[[ $? -eq 0 ]] || ex=1; _exit "yolo f"
+    while read line; do 
+        echo $line | cut -d " " -f 2 | sed 's/#.*//g'
+    done < ./functions | sed '1d;$d' > $tmpfuncs
+	[[ $? -ne 0 ]] && ex=1; _exit "functions not cooperating"
 }
 
 # Special files handled
@@ -270,11 +284,11 @@ _special(){
 # Finish him
 _sweep(){
     # Functions
-    { cat .funcs >> .vars && rm .funcs functions; } || { ex=1; _exit "could not sweep functions"; }
+    { cat $tmpfuncs >> $tmpvars && rm $tmpfuncs $tmpvars; } || { ex=1; _exit "could not sweep functions"; }
 		
     # Executive
-    { sed -i '1,4 d' $executive && cat $executive >> .vars; } && { rm "${executive}"; } || { ex=1; _exit "unable to sweep executive"; }
-    { mv .vars $executive && chmod +x $executive && rm vars; } || { ex=1; _exit "unable to sweep vars"; }
+    { sed -i '1,4 d' $executive && cat $executive >> $tmpvars; } && { rm "${executive}"; } || { ex=1; _exit "unable to sweep executive"; }
+    { mv $tmpvars $executive && chmod +x $executive && rm vars functions; } || { ex=1; _exit "unable to sweep vars"; }
 	
     [ $? -ne 0 ] && { ex=1; _exit "unable to '_sweep'"; }
     _special
@@ -289,7 +303,7 @@ _compile(){
         vars) _vars ;;
 		functions) _functions ;;
 	esac done
-	[ $? -ne 0 ] && ex=1; _exit "Compilation failure" # exit-code "system" needed
+	#[ "$?" -ne 0 ] && ex=1; _exit "Compilation failure" # exit-code "system" needed
     _sweep
 }
 
@@ -325,7 +339,7 @@ eval set -- "$opts"
 while :
 do
     case "$1" in
-        -s|--silent) QUIET=1; break ;;
+        -s|--silent) QUIET=1; shift 2 ; break ;;
         -h) _usage; break ;;
         --help) _read_man; break ;;
         -v) echo "$VERSION"; break ;;
@@ -340,8 +354,7 @@ do
 done
     
 case "$COMMAND" in
-    init) _setup "$2" ;;
-    # ! init) _setup_init "$@" ;;
+    init) _setup_init "$2" ;;
     del) _remove ;;
     lf) _list_functions ;;
     lv) _list_vars ;;
